config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # We only want two routes so we’ve added the restriction only: [:new, :create] .
  resource :contacts, only: [:new, :create]
  resource :visitors, only: [:new, :create]
  # The new route has these properties:
  #                             • new_contact_path – route helper
  # • contacts – name of the controller (ContactsController)
  # • new – controller action
  # • http://localhost:3000/contacts/new – URL generated by the route helper
  # • GET – HTTP method to display a page

  # The create route has these properties:
  # • contacts_path – route helper
  # • contacts – name of the controller (ContactsController)
  # • create – controller action
  # • http://localhost:3000/contacts – URL generated by the route helper
  # • POST – HTTP method to submit form data


  # resource :visitors
  # post 'contact', to: 'contacts#process_form'
  root 'visitors#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# class Contact < ActiveRecord::Base
#     # ActiveRecord gives us validation methods named validates_presence_of , validates_format_of ,
#     # and validates_length_of.
#     # has_no_table
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

  # It is not functional, I am going to focus on db
  # def update_spreadsheet
  #   connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
  #   ss = connection.spreadsheet_by_title('Learn-Rails-Example')
  #   # We look for a spreadsheet named “Learn-Rails-Example.” The first time we attempt to save
  #   # data, the spreadsheet will not exist, so we use the create_spreadsheet method to create it. If it
  #   # already exists, the spreadsheet_by_title method will find it.
  #   if ss.nil?
  #     ss = connection.create_spreadsheet('Learn-Rails-Example')
  #   end
  #   ws = ss.worksheets[0]
  #   last_row = 1 + ws.num_rows
  #   ws[last_row, 1] = Time.new
  #   ws[last_row, 2] = self.name
  #   ws[last_row, 3] = self.email
  #   ws[last_row, 4] = self.content
  #   ws.save
  # end
end

app/models/owner.rb
# class Owner
#
# def name
#     name = "Foobar Kadigan"
# end
#
# def birthdate
#     birthdate = Date.new(1992, 01, 03)
# end
#
# def countdown
#     today = Date.today
#     birthday = Date.new(birthdate.year, birthdate.month, birthdate.day)
#     if birthday > today
#         countdown = (birthday - today).to_i
#     end
# end
#
# end # Class end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  # has_no_table I will use sqlLite instead
  # Visitor.connection?

  attr_accessor :email, :string

  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i


  #Faraday::SSLError - SSL_connect returned=1 errno=0 state=error: certificate verify failed:

  def subscribe
    # mailchimp = Gibbon::Request.new(api_key: 'c89de8a4b155bdc9b665128591e1e122-us17')
    # list_id = '4bf4dcc763'
    result = -1;
    # result = mailchimp.lists(list_id).members.create(
    #     body: {
    #         email_address: self.email,
    #         status: 'subscribed'
    #     })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result != -1 else Rails.logger.info("Sorry, there was an error.")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
# Rails does all the work of extracting the form data from the browser’s POST request. Rails
# creates a hash with the form field data mapped to the form field labels and gives the hash the name of the form.
# params = {controller: 'contacts',
# action: 'process_form',
# contact: {name: 'Daniel', email: 'daniel@danielkehoe.com', content: 'hi!'}
# }
# The params hash includes these elements (plus others we won’t cover):
# • current controller
# • current action
# • form data (our contact hash)

#   We’ve dropped the “old school” process_form method and added the “Rails way” new and
#       create methods.
#   def process_form
#     # We use a logger.debug method to reveal the form data in our console log by revealing the
#     # contents of the params hash.
#     Rails.logger.debug "DEBUG: params are #{params}"
#     #We can retrieve the value of the name field with the expression params[:contact][:name] .
#     flash[:notice] = "Received request from #{params[:contact][:name]}"
#
#     # Directive to render the home page
#     redirect_to root_path
#   end

  def new
    # The controller new action will instantiate an empty Contact model, assign it to the @contact
    # instance variable, and render the app/views/contacts/new.html.erb view.
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    # Make sure that data is valid
    if @contact.valid?
      # TODO save data @contact.update_spreadsheet, not functional

      UserMailer.contact_email(@contact).deliver

      # There is no need to dig into to params no we can access directly from the model
      flash[:notice] = "Message sent from #{@contact.name}."
            redirect_to root_path(flash)
    else
      render :new
    end
  end

  private # Modifier
  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end
# Rails protects us from a class of security exploits called “mass-assignment vulnerabilities.”
# Rails won’t let us initialize a model with just any parameters submitted on a form. Suppose
# we were creating a new user and one of the user attributes was a flag allowing administrator
# access. A malicious hacker could create a fake form that provides a user name and sets the
# administrator status to “true.” Rails forces us to “white list” each of the parameters used to
# initialize the model.
#     We create a method named secure_params to screen the parameters sent from the browser.
#     The params hash contains two useful methods we use for our screening:
#   • require(:contact) – makes sure that params[:contact] is present
#   • permit(:name, :email, :content) – our “white list”
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def new
    Rails.logger.debug 'DEBUG: entering new method'
    # raise 'Deliberate Failure'

    # @owner = Owner.new
    # There is no need for this line as Flash
    # render 'visitors/new'

    # Flash allow to display a message temporarily, its a hash object in Ruby
    # We can assign other messages, such as flash[:alert] or even
    # flash[:warning]. In practice, Rails uses only :notice and :alert as flash message keys so it is
    # wise to stick with just these.
    # Assign the value to the key (flash[:key]=value), names are arbitrary but make them meaningful as follows
    # flash[:notice] = 'Welcome!'
    # flash[:alter] = 'My birthday is soon.'
    #
    # flash.each do |key, value|
    #   # Use key as the is class name and value as the value
    #   puts '<div class="' + key + '">' + value + '</div>'
    # end
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def secure_params
    params.require(:visitor).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact</h3>
<div class="form">
<%# Earlier, I explained that SimpleForm configures itself if we provide a model that inherits
from ActiveRecord. SimpleForm gives the form a name that matches the model name. And
SimpleForm generates a destination URL based on the model name %>
<%= simple_form_for @contact do |form| %>
<%# SimpleForm uses the @contact instance variable to name the form, set a destination for the
form data, and initialize each field in the form using attributes from the Contact model. %>
<%= form.error_notification %>
<%# We’ve added the error_notification method which provides all the error handling. The
method call is very simple but the results will be impressive. %>
<%= form.input :name, autofocus: true %> 
<%= form.input :email %>
<%= form.input :content, as: :text %>
<%= form.button :submit, 'Submit', class: 'submit' %>
<% end %>

<%# Setting the values for the form fields from the attributes in the model is called “binding the
form to the object” and you can read about it in the RailsGuides: Form Helpers article. %>
</div>

app/views/layouts/_footer.html.erb
<section class="small-4 columns">
<p>Copyright 2017.</p>
</section>
<section class="small-4 columns">
<p>All rights reserved.</p>
</section>

<%# Last 11/11/2017 %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
 <%# First, the expression, if msg.is_a?(String) serves as a test to make sure we only display messages that are strings. %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
             <%# Second, we use the Rails content_tag view helper to create the HTML div . The content_tag
helper eliminates the messy soup of angle brackets and quote marks we used to create the
HTML output in the example above. %>
     <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <%# . It is important to preserve the enclosing layout and
classes, even if you don’t want to display a site name or logo. The enclosing layout is used to
generate the navigation menu when the browser window shrinks to accommodate a tablet or
smartphone. %>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about')%></li>
<li><%= link_to 'Contact', new_contacts_path('contact') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
  <%# You’ll recall from the “Just Enough Ruby” chapter that it is a fancy conditional statement that says, “if
content_for?(:title) is present in the view file, use yield(:title) to include it, otherwise just
display ‘Learn Rails’.” %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%# Modernizr is required for Zurb Foundation %>
  <%# <%= javascript_include_tag 'vendor/modernizr' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%# The Rails asset pipeline utility is one of the most powerful features of the platform. It offers
convenience to the developer and helps organize an application; more importantly, it
improves the speed and responsiveness of any complex website.%>
  <%= csrf_meta_tags %>
</head>
<body>
<%#	 The <header> tag is typically used for branding or navigation. %>
<header>
  <%= render 'layouts/navigation' %>
</header>
<%#	<main role="main">, “The main content area of a document includes content that is unique
to that document and excludes content that is repeated across a set of documents such as site
navigation links, copyright information, site logos.” %>
<main role="main">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
</body>
<footer>
  <%= render 'layouts/footer' %>
</footer>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<%# We include a content_for Rails view helper that passes a page title to the application layout. %>
<h3>About Foobar Kadigan</h3>
<p>He was born in Waikikamukau, New Zealand. He left New Zealand for England, excelled
at the University of Mopery, and served in the Royal Loamshire Regiment. While in
service, he invented the kanuten valve used in the processing of unobtainium for
industrial use. He founded Acme Manufacturing, later acquired by the Advent
Corporation, to commercialize the product. Mr. Kadigan is now retired and lives in
Middlehampton where he raises Griadium frieda.</p>
<p>His favorite quotation is:</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua.</p>

app/views/pages/contact.html.erb
<% content_for :title do %>Contact<%end%>
<%# We include a content_for Rails view helper that passes a page title to the application layout. %>
<h3>Contact Me.</h3>
<div class="form">
<%# The simple_form_for view helper instantiates a form object which we assign to a variable
named form . %>
<%# The view helper simple_form_for requires parameters and a block.
Every form needs a name and a route in the application that will handle processing of the
form data. The parameters are:
• contact – the name of the form
• url – set to contact_path , the destination for the form data %>
<%= simple_form_for :contact, url: contact_path do |form| %>
<%# the form object is passed to the block and methods belonging to the form object are called to
produce HTML output. %>
<%# Each of the form methods takes various parameters, such as:
• autofocus – displays the cursor in the field
• as: :text – displays a multiline text area
• input_html – adds any HTML such as a CSS class
• class – applies a CSS class to modify a button’s appearance
Each line of code produces an element in the form
such as a field or a button. %>
<%= form.input :name, autofocus: true %>
<%= form.input :email %>
<%= form.input :content, as: :text %>
<%= form.button :submit, 'Submit', class: 'submit' %>
<% end %>
</div>

app/views/visitors/new.html.erb
<% content_for :title do %>Foobar Kadigan<% end %>
<% content_for :description do %>Website of Foobar Kadigan<% end %>
<section>

<%#  You can replace the placeholder photo with your own. Look for the app/assets/images folder
  and add an image. Instead of the HTML <img> tag, use the Rails image_tag view helper, like
  this:
  %= image_tag "myphoto.jpg" %>
  <img src="http://lorempixel.com/1170/600/cats/1">
</section>
<section>
  <div class="column">
    <h2>Stay in touch.</h2>
  </div>
  <div class="column">
    <div class="form-centered">
      <%= simple_form_for @visitor do |f| %>
        <%= f.error_notification %>
        <%= f.input :email, label: false, :placeholder => 'Your email address...' %>
        <br/>
        <%= f.button :submit, "Sign up for the newsletter", :class => "submit" %>
      <% end %>
    </div>
  </div>
</section>